#!/usr/bin/env node
// ============================================================
// scripts/build-config.js
// Reads .env → writes config.js for the Chrome extension.
// Run this once after cloning, or whenever you change .env:
//   node scripts/build-config.js
// ============================================================
"use strict";

const fs   = require("fs");
const path = require("path");

const ROOT      = path.resolve(__dirname, "..");
const ENV_PATH  = path.join(ROOT, ".env");
const CFG_PATH  = path.join(ROOT, "config.js");

// ── Parse .env (no external deps needed) ─────────────────────
function parseEnv(raw) {
  const vars = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, "");
    vars[key] = val;
  }
  return vars;
}

// ── Validate required keys ────────────────────────────────────
function validate(vars) {
  const required = [
    "GEMINI_API_KEY",
    "EMAILJS_SERVICE_ID",
    "EMAILJS_TEMPLATE_ID",
    "EMAILJS_PUBLIC_KEY",
  ];
  const missing = required.filter(k => !vars[k] || vars[k].startsWith("your_"));
  if (missing.length) {
    console.warn(
      "\n⚠  Warning: The following .env keys are still placeholders:\n" +
      missing.map(k => "   • " + k).join("\n") +
      "\n   Open .env and fill them in, then re-run this script.\n"
    );
  }
  return vars;
}

// ── Generate config.js ────────────────────────────────────────
function buildConfig(vars) {
  return `// ============================================================
// brif - Page Summarizer — Runtime Config
// ============================================================
// AUTO-GENERATED by scripts/build-config.js — do not edit.
// Re-run:  node scripts/build-config.js
// ============================================================

window.APP_CONFIG = {
  geminiApiKey: ${JSON.stringify(vars.GEMINI_API_KEY || "")},
  emailjs: {
    serviceId:  ${JSON.stringify(vars.EMAILJS_SERVICE_ID  || "")},
    templateId: ${JSON.stringify(vars.EMAILJS_TEMPLATE_ID || "")},
    publicKey:  ${JSON.stringify(vars.EMAILJS_PUBLIC_KEY  || "")},
  },
};
`;
}

// ── Main ──────────────────────────────────────────────────────
if (!fs.existsSync(ENV_PATH)) {
  console.error(
    "\n✗  .env not found. Copy .env.example to .env and fill in your keys:\n" +
    "   cp .env.example .env\n"
  );
  process.exit(1);
}

const raw    = fs.readFileSync(ENV_PATH, "utf8");
const vars   = validate(parseEnv(raw));
const output = buildConfig(vars);

fs.writeFileSync(CFG_PATH, output, "utf8");
console.log("✓  config.js written from .env");
